-- 110 national teams, additive + backfill only. Safe to run against a live DB:
-- updates crest_url on any existing team with a matching name (e.g. manually-added
-- 'England'/'France' rows), then inserts every team that doesn't exist yet.
-- Does NOT touch players, draft_picks, matches, or tournament_state.

update teams set crest_url = v.crest_url
from (values
  ('Argentina', '/flags/argentina.png'),
  ('Belgium', '/flags/belgium.png'),
  ('Spain', '/flags/spain.png'),
  ('Canada', '/flags/canada.png'),
  ('Mexico', '/flags/mexico.png'),
  ('United States', '/flags/united-states.png'),
  ('Australia', '/flags/australia.png'),
  ('Iraq', '/flags/iraq.png'),
  ('Iran', '/flags/iran.png'),
  ('Japan', '/flags/japan.png'),
  ('Jordan', '/flags/jordan.png'),
  ('South Korea', '/flags/south-korea.png'),
  ('Qatar', '/flags/qatar.png'),
  ('Saudi Arabia', '/flags/saudi-arabia.png'),
  ('Uzbekistan', '/flags/uzbekistan.png'),
  ('Algeria', '/flags/algeria.png'),
  ('Cape Verde', '/flags/cape-verde.png'),
  ('DR Congo', '/flags/democratic-republic-of-congo.png'),
  ('Egypt', '/flags/egypt.png'),
  ('Ghana', '/flags/ghana.png'),
  ('Morocco', '/flags/morocco.png'),
  ('Senegal', '/flags/senegal.png'),
  ('South Africa', '/flags/south-africa.png'),
  ('Tunisia', '/flags/tunisia.png'),
  ('Haiti', '/flags/haiti.png'),
  ('Panama', '/flags/panama.png'),
  ('Brazil', '/flags/brazil.png'),
  ('Colombia', '/flags/colombia.png'),
  ('Ecuador', '/flags/ecuador.png'),
  ('Paraguay', '/flags/paraguay.png'),
  ('Uruguay', '/flags/uruguay.png'),
  ('New Zealand', '/flags/new-zealand.png'),
  ('Austria', '/flags/austria.png'),
  ('Bosnia and Herzegovina', '/flags/bosnia-and-herzegovina.png'),
  ('Croatia', '/flags/croatia.png'),
  ('Czech Republic', '/flags/czech-republic.png'),
  ('England', '/flags/england.png'),
  ('France', '/flags/france.png'),
  ('Germany', '/flags/germany.png'),
  ('Netherlands', '/flags/netherlands.png'),
  ('Norway', '/flags/norway.png'),
  ('Portugal', '/flags/portugal.png'),
  ('Scotland', '/flags/scotland.png'),
  ('Sweden', '/flags/sweden.png'),
  ('Switzerland', '/flags/switzerland.png'),
  ('Turkey', '/flags/turkey.png'),
  ('Denmark', '/flags/denmark.png'),
  ('Finland', '/flags/finland.png'),
  ('Hungary', '/flags/hungary.png'),
  ('Iceland', '/flags/iceland.png'),
  ('Republic of Ireland', '/flags/ireland.png'),
  ('Italy', '/flags/italy.png'),
  ('Poland', '/flags/poland.png'),
  ('Romania', '/flags/romania.png'),
  ('Ukraine', '/flags/ukraine.png'),
  ('Wales', '/flags/wales.png'),
  ('Nigeria', '/flags/nigeria.png'),
  ('Cameroon', '/flags/cameroon.png'),
  ('Mali', '/flags/mali.png'),
  ('Zambia', '/flags/zambia.png'),
  ('Guinea', '/flags/guinea.png'),
  ('Burkina Faso', '/flags/burkina-faso.png'),
  ('Angola', '/flags/angola.png'),
  ('Zimbabwe', '/flags/zimbabwe.png'),
  ('Libya', '/flags/libya.png'),
  ('Sudan', '/flags/sudan.png'),
  ('Gabon', '/flags/gabon.png'),
  ('Benin', '/flags/benin.png'),
  ('Togo', '/flags/togo.png'),
  ('Sierra Leone', '/flags/sierra-leone.png'),
  ('Rwanda', '/flags/rwanda.png'),
  ('Uganda', '/flags/uganda.png'),
  ('Kenya', '/flags/kenya.png'),
  ('Equatorial Guinea', '/flags/equatorial-guinea.png'),
  ('China', '/flags/china.png'),
  ('India', '/flags/india.png'),
  ('Thailand', '/flags/thailand.png'),
  ('Vietnam', '/flags/vietnam.png'),
  ('Indonesia', '/flags/indonesia.png'),
  ('Malaysia', '/flags/malaysia.png'),
  ('United Arab Emirates', '/flags/united-arab-emirates.png'),
  ('Israel', '/flags/israel.png'),
  ('Lebanon', '/flags/lebanon.png'),
  ('Syria', '/flags/syria.png'),
  ('Kuwait', '/flags/kuwait.png'),
  ('Kazakhstan', '/flags/kazakhstan.png'),
  ('North Korea', '/flags/north-korea.png'),
  ('Russia', '/flags/russia.png'),
  ('Serbia', '/flags/serbia.png'),
  ('Slovenia', '/flags/slovenia.png'),
  ('Slovakia', '/flags/slovakia.png'),
  ('Bulgaria', '/flags/bulgaria.png'),
  ('Greece', '/flags/greece.png'),
  ('Cyprus', '/flags/cyprus.png'),
  ('Albania', '/flags/albania.png'),
  ('North Macedonia', '/flags/north-macedonia.png'),
  ('Montenegro', '/flags/montenegro.png'),
  ('Belarus', '/flags/belarus.png'),
  ('Georgia', '/flags/georgia.png'),
  ('Armenia', '/flags/armenia.png'),
  ('Azerbaijan', '/flags/azerbaijan.png'),
  ('Chile', '/flags/chile.png'),
  ('Peru', '/flags/peru.png'),
  ('Venezuela', '/flags/venezuela.png'),
  ('Bolivia', '/flags/bolivia.png'),
  ('Costa Rica', '/flags/costa-rica.png'),
  ('Honduras', '/flags/honduras.png'),
  ('Jamaica', '/flags/jamaica.png'),
  ('Trinidad and Tobago', '/flags/trinidad-and-tobago.png'),
  ('Cuba', '/flags/cuba.png')
) as v(name, crest_url)
where teams.name = v.name and teams.crest_url is null;

insert into teams (name, crest_url)
select v.name, v.crest_url from (values
  ('Argentina', '/flags/argentina.png'),
  ('Belgium', '/flags/belgium.png'),
  ('Spain', '/flags/spain.png'),
  ('Canada', '/flags/canada.png'),
  ('Mexico', '/flags/mexico.png'),
  ('United States', '/flags/united-states.png'),
  ('Australia', '/flags/australia.png'),
  ('Iraq', '/flags/iraq.png'),
  ('Iran', '/flags/iran.png'),
  ('Japan', '/flags/japan.png'),
  ('Jordan', '/flags/jordan.png'),
  ('South Korea', '/flags/south-korea.png'),
  ('Qatar', '/flags/qatar.png'),
  ('Saudi Arabia', '/flags/saudi-arabia.png'),
  ('Uzbekistan', '/flags/uzbekistan.png'),
  ('Algeria', '/flags/algeria.png'),
  ('Cape Verde', '/flags/cape-verde.png'),
  ('DR Congo', '/flags/democratic-republic-of-congo.png'),
  ('Egypt', '/flags/egypt.png'),
  ('Ghana', '/flags/ghana.png'),
  ('Morocco', '/flags/morocco.png'),
  ('Senegal', '/flags/senegal.png'),
  ('South Africa', '/flags/south-africa.png'),
  ('Tunisia', '/flags/tunisia.png'),
  ('Haiti', '/flags/haiti.png'),
  ('Panama', '/flags/panama.png'),
  ('Brazil', '/flags/brazil.png'),
  ('Colombia', '/flags/colombia.png'),
  ('Ecuador', '/flags/ecuador.png'),
  ('Paraguay', '/flags/paraguay.png'),
  ('Uruguay', '/flags/uruguay.png'),
  ('New Zealand', '/flags/new-zealand.png'),
  ('Austria', '/flags/austria.png'),
  ('Bosnia and Herzegovina', '/flags/bosnia-and-herzegovina.png'),
  ('Croatia', '/flags/croatia.png'),
  ('Czech Republic', '/flags/czech-republic.png'),
  ('England', '/flags/england.png'),
  ('France', '/flags/france.png'),
  ('Germany', '/flags/germany.png'),
  ('Netherlands', '/flags/netherlands.png'),
  ('Norway', '/flags/norway.png'),
  ('Portugal', '/flags/portugal.png'),
  ('Scotland', '/flags/scotland.png'),
  ('Sweden', '/flags/sweden.png'),
  ('Switzerland', '/flags/switzerland.png'),
  ('Turkey', '/flags/turkey.png'),
  ('Denmark', '/flags/denmark.png'),
  ('Finland', '/flags/finland.png'),
  ('Hungary', '/flags/hungary.png'),
  ('Iceland', '/flags/iceland.png'),
  ('Republic of Ireland', '/flags/ireland.png'),
  ('Italy', '/flags/italy.png'),
  ('Poland', '/flags/poland.png'),
  ('Romania', '/flags/romania.png'),
  ('Ukraine', '/flags/ukraine.png'),
  ('Wales', '/flags/wales.png'),
  ('Nigeria', '/flags/nigeria.png'),
  ('Cameroon', '/flags/cameroon.png'),
  ('Mali', '/flags/mali.png'),
  ('Zambia', '/flags/zambia.png'),
  ('Guinea', '/flags/guinea.png'),
  ('Burkina Faso', '/flags/burkina-faso.png'),
  ('Angola', '/flags/angola.png'),
  ('Zimbabwe', '/flags/zimbabwe.png'),
  ('Libya', '/flags/libya.png'),
  ('Sudan', '/flags/sudan.png'),
  ('Gabon', '/flags/gabon.png'),
  ('Benin', '/flags/benin.png'),
  ('Togo', '/flags/togo.png'),
  ('Sierra Leone', '/flags/sierra-leone.png'),
  ('Rwanda', '/flags/rwanda.png'),
  ('Uganda', '/flags/uganda.png'),
  ('Kenya', '/flags/kenya.png'),
  ('Equatorial Guinea', '/flags/equatorial-guinea.png'),
  ('China', '/flags/china.png'),
  ('India', '/flags/india.png'),
  ('Thailand', '/flags/thailand.png'),
  ('Vietnam', '/flags/vietnam.png'),
  ('Indonesia', '/flags/indonesia.png'),
  ('Malaysia', '/flags/malaysia.png'),
  ('United Arab Emirates', '/flags/united-arab-emirates.png'),
  ('Israel', '/flags/israel.png'),
  ('Lebanon', '/flags/lebanon.png'),
  ('Syria', '/flags/syria.png'),
  ('Kuwait', '/flags/kuwait.png'),
  ('Kazakhstan', '/flags/kazakhstan.png'),
  ('North Korea', '/flags/north-korea.png'),
  ('Russia', '/flags/russia.png'),
  ('Serbia', '/flags/serbia.png'),
  ('Slovenia', '/flags/slovenia.png'),
  ('Slovakia', '/flags/slovakia.png'),
  ('Bulgaria', '/flags/bulgaria.png'),
  ('Greece', '/flags/greece.png'),
  ('Cyprus', '/flags/cyprus.png'),
  ('Albania', '/flags/albania.png'),
  ('North Macedonia', '/flags/north-macedonia.png'),
  ('Montenegro', '/flags/montenegro.png'),
  ('Belarus', '/flags/belarus.png'),
  ('Georgia', '/flags/georgia.png'),
  ('Armenia', '/flags/armenia.png'),
  ('Azerbaijan', '/flags/azerbaijan.png'),
  ('Chile', '/flags/chile.png'),
  ('Peru', '/flags/peru.png'),
  ('Venezuela', '/flags/venezuela.png'),
  ('Bolivia', '/flags/bolivia.png'),
  ('Costa Rica', '/flags/costa-rica.png'),
  ('Honduras', '/flags/honduras.png'),
  ('Jamaica', '/flags/jamaica.png'),
  ('Trinidad and Tobago', '/flags/trinidad-and-tobago.png'),
  ('Cuba', '/flags/cuba.png')
) as v(name, crest_url)
where not exists (select 1 from teams where teams.name = v.name);
